name: Install CocoaPods

on: Prem/Movies

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby and CocoaPods
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ruby-full
        sudo gem install cocoapods
        pod --version
